### ISSUE TITLE
Bug in gradle parser: versioneye does not detect groovy dependencies in build.gradle

### ISSUE THREAD

**Issue by ascheman** [versioneye/versioneye_issues#1]
VersionEye does not correctly detect groovy dependencies in a build.gradle file, eg., 

```
...
    groovy "org.codehaus.groovy:groovy:2.1.+"
...
```

from https://github.com/ascheman/tictactoe/blob/master/build.gradle

**Comment by reiz** [comment]
The current implementation assumes that the first part is the scope of the dependency. Is "groovy" just another scope? Or should we treat it in a different way?

**Comment by ascheman** [comment]
Well, the "groovy" dependency declares the used groovy version (through the gradle groovy plugin). Otherwise the groovy version coming with the gradle version is used (this seems to become deprecated with Gradle 2.0).

In the sample above I have changed the dependency to a compile dependency.

**Comment by reiz** [comment]
Ok. That helps. Thank you for the input.

**Comment by reiz** [comment]
@ascheman I just updated the Gradle parser. It works now. Here is the project on VersionEye: https://www.versioneye.com/user/projects/53f4a26ee09da34691000001 

Do you know already the Gradle VersionEye Plugin? 
https://github.com/stempler/gradle-versioneye-plugin 
It resolves dependencies natively on localhost and sends the dependencies to the VersionEye API.
