### ISSUE TITLE
Flat style badges

### ISSUE THREAD

**Issue by niclashoyer** [versioneye/versioneye_issues#11]
It would be nice if versioneye supported the new [shields.io](http://shields.io) [flat style badges](https://github.com/badges/shields/pull/159), e.g.

```
.../badge.svg?style=flat
```

![http://img.shields.io/badge/dependencies-out%20of%20date-yellow.svg?style=flat](http://img.shields.io/badge/dependencies-out%20of%20date-yellow.svg?style=flat)

**Comment by reiz** [comment]
Good idea. Let me see what I can do.

**Comment by reiz** [comment]
Done! 

Example: https://www.versioneye.com/java/org.apache.httpcomponents:httpclient/4.3.3 

Now we use flat style badges by default. If you remove the flat param you get the old ones.

**Comment by niclashoyer** [comment]
great!
