### ISSUE TITLE
Fix link to Nexus repository

### ISSUE THREAD

**Issue by jcarsique** [versioneye/versioneye_issues#13]
Hi,

In a Nexus repository, the dots in the groupId must be converted to slashes in the URL.

For instance, the "Link to Repository" for [org.nuxeo.ecm.platform:nuxeo-admin-center:5.6](https://www.versioneye.com/java/org.nuxeo.ecm.platform:nuxeo-admin-center/5.6) is:
https://maven.nuxeo.org/nexus/content/repositories/public-releases/org.nuxeo.ecm.platform/nuxeo-admin-center
whereas it should be:
http://maven.nuxeo.org/nexus/content/repositories/public-releases/org/nuxeo/ecm/platform/nuxeo-admin-center (plus, optionally, a trailing "/5.6/" for the version).

**Comment by reiz** [comment]
@jcarsique I just fixed it. Will deploy it today to production.

**Comment by reiz** [comment]
@jcarsique OK. It's fixed on production!
