### ISSUE TITLE
API: minor problem with products {lang} field

### ISSUE THREAD

**Issue by stephanadler** [versioneye/versioneye_issues#14]
If I use the API to search for a product (i.e. https://www.versioneye.com/api/v2/products/search/urlsafe-base64) the "language" field shows the value "Node.JS". However I can not use this string directly to construct the URL to get to the product info itself, as {lang} is expected to be "nodejs" in this case (i.e. https://www.versioneye.com/api/v2/products/nodejs/node-base64-urlsafe).

This is not hard to work around, but counter-intuitive and a bit tricky to figure out.

**Comment by reiz** [comment]
@stephanadler It's fixed now. 

Next time please post here: https://bitbucket.org/versioneye/versioneye/issues
