### ISSUE TITLE
API: hard to get from dependency to product

### ISSUE THREAD

**Issue by stephanadler** [versioneye/versioneye_issues#15]
In my use case I want to get from an outdated dependency I get from
https://www.versioneye.com/api/v2/projects/{project_id}?api_key=xxxxxxxxxxxxxxxxx to the information for the product. However this seems to be a bit tricky, as there is not language information in dependencies[] or in the project itself and I am therefore not able to trivially construct /v2/products/{lang}/{prod_key}.

**Comment by reiz** [comment]
True story. I will add it, that's not a big deal.

**Comment by reiz** [comment]
@stephanadler OK. I just added the language information to the project dependencies. Let me know if you need more ;-)
