### ISSUE TITLE
Spelling mistake in error response for /v2/github/{repo_key}

### ISSUE THREAD

**Issue by zsturgess** [versioneye/versioneye_issues#16]
![screenshot from 2015-08-31 23 43 08](https://cloud.githubusercontent.com/assets/3624596/9592361/2c7a4124-503a-11e5-819a-633791f1d68e.png)

The response body should probably read:

```
{
  "error": "We couldn't find the repository `55d4fbf46dbe17001e0000d6` in your account."
}
```

The picky, OCD part of me spotted this one :)

**Comment by zsturgess** [comment]
(And yes, I reset my API key before I posted ;) )

**Comment by reiz** [comment]
Thanks man. I just improved the spelling. It goes online with the next deployment ;-)

**Comment by reiz** [comment]
@zsturgess The new version is deployed. Many thanks for helping to improve the product :+1:
