### ISSUE TITLE
LATEST version for dependencies in maven project

### ISSUE THREAD

**Issue by herau** [versioneye/versioneye_issues#17]
`LATEST` version isn't supported (test only with integration with a github project). VersionEye always says that dependencies aren't up to date.

**Comment by reiz** [comment]
@herau What for a project file? `pom.xml`, `package.json` or something else? Can you post a link to the project?

**Comment by herau** [comment]
@reiz 
It's for a maven project (pom.xml)
You can test with the project :https://github.com/herau/diy-project

Maven support `release` and `latest` value for version so it will be great to have a support in versionEye.

**Comment by reiz** [comment]
@herau I see. `LATEST` stands for the latest unstable version and `RELEASE` for the latest stable version. Will extend the pom.xml parser and ass some tests.

**Comment by herau** [comment]
@reiz thanks, it's à good news :-)

**Comment by reiz** [comment]
@herau It's fixed now. You have to click the "Re Parse Now" button on the project page. Please try again and confirm that it works for you.

**Comment by herau** [comment]
It's work for me. Thank you @reiz
