### ISSUE TITLE
Requested GitHub permissions too broad

### ISSUE THREAD

**Issue by sschuberth** [versioneye/versioneye_issues#18]
When trying to sign-in to VersionEye via GitHub, I realized that the requested repository permissions are very broad:

```
This application will be able to read and write all public and private repository data. This includes the following:

    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
```

Shouldn't read-only access to the "Code" and write access to "Webhooks and services" be enough?

Similarly, why does VersionEye need to access the Organizations data?

**Comment by reiz** [comment]
Hi @sschuberth. Unfortunately we need write access to read private repositories. And we need access to Organisations to access repositories inside of organisations. Here is a more detailed blog post about why the scope is so wide: http://blog.versioneye.com/2015/08/11/why-the-oauth-github-scope-was-changed/. 

But indeed we don't have a single git write operation in our code base. VersionEye is only reading data! 

If you feel unconvertible with that you can still use the [API](https://www.versioneye.com/api/). That way you have more control and there are already a lot of Plugins/AddOns for the API.
