### ISSUE TITLE
maven-release-plugin:3.0-r1585899 is not in central

### ISSUE THREAD

**Issue by jinahya** [versioneye/versioneye_issues#19]
Vresioneye, in my [project](https://www.versioneye.com/user/projects/5652ef1dff016c00330005b0), keeps reporting `maven-release-plugin:2.5.3` is outdated over `maven-release-plugin:3.0-r1585899` which is not in [Maven Central](http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-release-plugin/). And I believe my `pom.xml` does't have any external repositories set.

**Comment by reiz** [comment]
Should be fixed now.
