### ISSUE TITLE
Bug in gradle parser (or feature request?): include sub modules from settings.gradle

### ISSUE THREAD

**Issue by ascheman** [versioneye/versioneye_issues#2]
VersionEye should work with gradle sub modules, i.e., if the settings.gradle contains an include:

```
include "tictactoe-core", "tictactoe-web"
```

(Sample from https://github.com/ascheman/tictactoe/blob/master/settings.gradle)

**Comment by reiz** [comment]
OK. Will checkout the documentation of Gradle submodules.

**Comment by reiz** [comment]
We don't resolve file dependencies via the GitHub API. That is too time expensive. For more complex Gradle builds I recommend the Gradle VersionEye Plugin from @stempler: 
https://github.com/stempler/gradle-versioneye-plugin
It resolves dependencies locally and sends only the resolved dependencies to the VersionEye API. Our Enterprise clients execute these (Or the Maven) Plugin every night on their CI System.
