### ISSUE TITLE
/python/bidict is out of sync

### ISSUE THREAD

**Issue by jab** [versioneye/versioneye_issues#20]
https://www.versioneye.com/python/bidict is redirecting to 0.9.0 which it shows as the "current" release, however if you go to https://pypi.python.org/pypi/bidict you'll see that's several versions behind and the current release is 0.10.0.post1. Could you please update it on versioneye, and if this isn't just a one-time thing (i.e. it's possible for versions to drift out of sync in the future), provide a sync button on a project page so users can request a sync more easily?

**Comment by jab** [comment]
![screen shot 2015-12-23 at 18 37 14](https://cloud.githubusercontent.com/assets/64992/11986955/b1facd1e-a9a4-11e5-8336-258e927a8aa7.png)

**Comment by jab** [comment]
![screen shot 2015-12-23 at 18 41 19](https://cloud.githubusercontent.com/assets/64992/11986962/c8d3f89e-a9a4-11e5-9ed8-1d4c75a83589.png)

**Comment by jab** [comment]
That's weird, I got an email from VersionEye ~10 hours after I opened this informing me that bidict had been updated to 0.10.0. So VersionEye is still out of sync, but now it's only 1 release behind the latest.
![screen shot 2015-12-24 at 14 54 15](https://cloud.githubusercontent.com/assets/64992/11997635/8c969af8-aa4e-11e5-9f41-f3f23c63f76e.png)
![screen shot 2015-12-24 at 14 55 53](https://cloud.githubusercontent.com/assets/64992/11997636/8c96e2a6-aa4e-11e5-805d-48b6c4dbf53d.png)

**Comment by jab** [comment]
https://www.versioneye.com/python/bidict still erroneously showing 0.10.0 as latest. Any ideas?

**Comment by reiz** [comment]
Hey @jab. I think VersionEye is in sync. but there is an issue with the versions and the recognition of the newest. The version `0.10.0.post1` is actually there. See here the screenshot. 

![screen shot 2016-01-08 at 10 41 52](https://cloud.githubusercontent.com/assets/652130/12195026/b7ed3e26-b5f4-11e5-9f5f-6045404ac8ec.png)

VersionEye is using semantic versioning to recognise the newest version, unfortunately `0.10.0.post1` isn't semantic versioning. The code which is doing the version sorting is open source. You can find it here: https://github.com/versioneye/naturalsorter. Feel free to add test cases or send a pull request ;-)

**Comment by jab** [comment]
@reiz In Python-land (e.g. with PyPI, pip, and other tools), PEP 0440 trumps semantic versioning, and decrees that post-releases should be of this format:
https://www.python.org/dev/peps/pep-0440/#post-releases

Don't have time to open an issue elsewhere or work up a PR at the moment, but since this is making your site behave incorrectly for Python packages which follow the Python versioning standard, hope you can follow up.
