### ISSUE TITLE
discrepancy between projects watched and followed

### ISSUE THREAD

**Issue by jab** [versioneye/versioneye_issues#21]
When I go to https://www.versioneye.com/user/projects it shows "VersionEye is watching 0 Projects for you" but when I go to https://www.versioneye.com/users/jab it says "Follows 24 Packages".
![screen shot 2015-12-23 at 18 36 11](https://cloud.githubusercontent.com/assets/64992/11986992/3339da32-a9a5-11e5-80d4-5bcd1b3776e8.png)
![screen shot 2015-12-23 at 18 42 47](https://cloud.githubusercontent.com/assets/64992/11986993/333a4562-a9a5-11e5-9361-f1ac49026cc7.png)

**Comment by jab** [comment]
Am I misunderstanding something here?

**Comment by reiz** [comment]
@jab Indeed you misunderstood something :) The "Follows 24 Packages" on your profile page are packages which you follow directly. That are public software packages which are available through the search. For example the [Django](https://www.versioneye.com/python/django/1.9.5) package. If you click the follow button on the page its a package you follow and as soon a new version comes out you get an email notification. 

The projects under `/users/projects` are your private projects, which are not available in the public search. You can create a VersionEye project by uploading a `requirements.txt` file for example or you can use the GitHub integration to let VersionEye monitor your `setup.py` or `requirements.txt` directly at GitHub. That way VersionEye will parse all the project dependencies and notify you about out-dated dependencies in your project and about security vulnerabilities.
