### ISSUE TITLE
offer option of only asking for github public repo access

### ISSUE THREAD

**Issue by jab** [versioneye/versioneye_issues#22]
When you try to connect VersionEye to GitHub, VersionEye requests permission to access your private repos as well as your public repos. There appears to be no way to only give VersionEye access to your public repos.

![screen shot 2015-12-23 at 18 45 27](https://cloud.githubusercontent.com/assets/64992/11987006/62d4306c-a9a5-11e5-8839-04f858d7ba8c.png)

**Comment by reiz** [comment]
Done! Simply use the 2nd "Login with GitHub" button on the [sign in](https://www.versioneye.com/signin?utf8=%E2%9C%93) page. 

![screen shot 2016-01-04 at 20 37 32](https://cloud.githubusercontent.com/assets/652130/12098527/33d7a6b8-b323-11e5-8cd6-60c9ac2797ea.png)

Feel free to reopen this ticket if it doesn't work for you.

**Comment by jab** [comment]
I already created an account via email. When I log in and go to https://www.versioneye.com/settings/connect, there's still only a single "Connect with GitHub" option, and it still asks for private repo access.

I'd reopen this ticket, but I don't have permission.

**Comment by reiz** [comment]
@jab Ah yes. Forgot that settings section to customise :) Will do that now.

**Comment by reiz** [comment]
@jab OK. Just updated that section as well.

**Comment by jab** [comment]
Thanks, public GitHub connect appears to have worked.
