### ISSUE TITLE
Some Python deps don't get picked up

### ISSUE THREAD

**Issue by wldhx** [versioneye/versioneye_issues#24]
[The project in question](https://www.versioneye.com/user/projects/576509630735400045bbfcc1).

While dependencies do get parsed correctly, some of them (`matrix-client`, `confuse`, a few others) are shown as unknown while being listed on PyPI and even in VersionEye's own DB (i.e. appear in search results).

**Comment by reiz** [comment]
It was fixed with this [commit](https://github.com/versioneye/versioneye-core/commit/15bfc4a7e5c387a707a2cd5ea858aa117e5c7109). Your project is updated now. See [here](https://www.versioneye.com/user/projects/576509630735400045bbfcc1?child=5765810e0735400043c1be62#tab-dependencies):

**Comment by wldhx** [comment]
@reiz It did indeed fix `requirements.txt` deps, but some of [`requirements-dev.txt`](https://www.versioneye.com/user/projects/576509630735400045bbfcc1?child=5778b75368ee07004d8f9096#tab-dependencies) are still left out.

**Comment by reiz** [comment]
@wldhx I take a look after lunch.

**Comment by reiz** [comment]
@wldhx Just notice that `pre-commit` is spelled wrong. There is no such package. On PyPI and VersionEye the package is available as `pre_commit`, with underscore. See here: https://www.versioneye.com/python/pre_commit/0.8.2 and https://pypi.python.org/pypi/pre_commit.

**Comment by wldhx** [comment]
@reiz Well, that's weird. It's [site](http://pre-commit.com/#install) uses the dash version. And `$ pip install pre-commit` happily executes.

**Comment by reiz** [comment]
@wldhx OK. Then maybe it doesn't matter if it is `-` or `_`. I can implement it the same way for VersionEye.

**Comment by reiz** [comment]
@wldhx OK. `pre-commit` is recognized now by VersionEye, see [here](https://www.versioneye.com/user/projects/576509630735400045bbfcc1?child=5778b75368ee07004d8f9096#tab-dependencies). 

I'm not a python guy. Can you explain the syntax of this line please: 

```
prospector[with_pyroma,with_vulture]>=0.11.7
```

The package `prospector` is available on VersionEye, but what is the meaning of the brackets?

**Comment by wldhx** [comment]
@reiz 

> dash/underscore

Yeah, I now recall the discussions on that somewhere in the mailing lists. Tl;dr current setuptools automatically transform `_` to `-` for packages, but we still have quite a few packages with `_`. Pip also automatically translates `_` to `-`.

> what is the meaning of the brackets

That's a [feature of setuptools](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) called 'extras', see [prospector's setup.py](https://github.com/landscapeio/prospector/blob/master/setup.py#L95). Basically, you can declare optional dependency groups with them.

The naive approach would be just dropping the brackets and their contents, but than we wouldn't get all the deps. Looks like the parser should be extended to handle them.

**Comment by reiz** [comment]
@wldhx OK. For right now I just removed the brackets at parsing time. Here is the current result: https://www.versioneye.com/user/projects/576509630735400045bbfcc1?child=5778b75368ee07004d8f9096#tab-dependencies. 

By the way, VersionEye is open source and [here](https://github.com/versioneye/versioneye-core/blob/master/lib/versioneye/parsers/requirements_parser.rb) is the code for the requirement parser and here are the [tests](https://github.com/versioneye/versioneye-core/blob/master/spec/versioneye/parsers/requirements_parser_spec.rb).

**Comment by wldhx** [comment]
@reiz Ok, thanks a lot for your help.

I'm not much acquainted with Ruby, but I'll see what I can do. 

As a side-note, I think we should create a separate issue for extras parsing.

**Comment by reiz** [comment]
@wldhx Yes. Please create a separate issue for that. You can open the ticket directly here in this repository: https://github.com/versioneye/versioneye-core. That's where it belongs to.
