### ISSUE TITLE
jsdoc-baseline is not recognised 

### ISSUE THREAD

**Issue by Nir-Tal** [versioneye/versioneye_issues#25]
The link is broken.
https://www.versioneye.com/nodejs/jsdoc-baseline/git+https://github.com/hegemonic/baseline.git#d161c4136e12ca5d5674747d4b115067a6980185

The version is shown as git link

**Comment by reiz** [comment]
Hi @Nir-Tal Can you please post a link to your project there the link appears?

**Comment by Nir-Tal** [comment]
Hi,

Here you go 
https://www.versioneye.com/user/projects/592d1ad6c0295d003c403665#tab-dependencies

**Comment by reiz** [comment]
@Nir-Tal Thanks. Looks like a bug.

**Comment by reiz** [comment]
@Nir-Tal OK. It's fixed now. See here: https://www.versioneye.com/user/projects/592d1ad6c0295d003c403665#tab-dependencies.

**Comment by Nir-Tal** [comment]
Sorry but it's not yet 100% working..
The file now show Unknown on the summary and the license version when entering the dependency.

**Comment by reiz** [comment]
@Nir-Tal Hm. I see. The VersionEye database is build that way that every version of a dependency has his own set of licenses. Licenses can change from version to version. We have a license for the version `0.0.1-dev` of jsdoc-baseline. But we don't have a license for jsdoc-baseline and that particular commit link. We would have to crawl that directly from GitHub and that's a bit more complicated then just reading it from the NPMRegistry. 

I would say that is a new feature request which we have to think about. Can you open a new ticket for that please? 

For right now you could also put that dependency on a component whitelist. The entry would be `nodejs:jsdoc-baseline`. Then the dependency would be whitelisted and it wouldn't cause any error in GitHub pull requests.
