### ISSUE TITLE
VersionEye should support multi-module maven projects or support multiple pom.xml files per repository

### ISSUE THREAD

**Issue by Laures** [versioneye/versioneye_issues#4]
I'm working a lot with multi module java projects. currently i can only select one pom file per repository (i assume). if i try to select a second pom from the same branch i get an error message.

it would be great if versioneye could detect multimodule projects automaticly and would follow the modules information in the top level pom.

it would be ok if i could start multiple projects from the same branch of the same repository. this way i could import every module in itself.

**Comment by reiz** [comment]
Currently we don't support that via the Web App. But we have a maven plugin which is doing exactly that. Did you try the versioneye_maven_plugin? 

https://github.com/versioneye/versioneye_maven_plugin

**Comment by Laures** [comment]
i will try it today. looks promising.

**Comment by Laures** [comment]
works in general. there were a number of problems that i will create issues for.
