### ISSUE TITLE
Link to homepage and/or changelog

### ISSUE THREAD

**Issue by matze** [versioneye/versioneye_issues#6]
I just repeat here – for better visibility and transparency – what I wrote in your feedback form. VersionEye is great at telling me which release was but not so much _what_ has changed. I know, it'll be difficult to link or even parse the change logs but it would help a lot. If that's not possible at least a link to the homepage of the project would be nice to have.

**Comment by reiz** [comment]
Hey @matze. Totally get your point. We show always a link to the project page if available. Unfortunately most Maven projects don't have a homepage in their pom.xml registered. In this cases we can only display a link to the maven repository. 

But we are working on fetching release notes from GitHub, if available. We started already to work on that. That will come in future ;-)
