### ISSUE TITLE
Feature request: Add a note field when adding a project

### ISSUE THREAD

**Issue by marclaporte** [versioneye/versioneye_issues#8]
I am tracking 2 projects here:
https://www.versioneye.com/user/projects

I am tracking 12.x LTS and trunk for Tiki. On the list, they both come out as tiki/tiki. With a note/comment field, I could indicate what I am tracking and with personal notes of why, what to look for, etc.

**Comment by reiz** [comment]
@marclaporte Yes. VersionEye tries to parse the project name directly from the project file. If that is not available the project will be named like the the filename. But you can rename the projects afterwards, in the project detail view. See the screenshots here.

![screen shot 2015-06-17 at 20 27 24](https://cloud.githubusercontent.com/assets/652130/8215361/a5919e4a-152f-11e5-996d-d6be2ea2715d.png)

![screen shot 2015-06-17 at 20 28 30](https://cloud.githubusercontent.com/assets/652130/8215370/affe1c1e-152f-11e5-8b68-38bbb3f97d50.png)

**Comment by marclaporte** [comment]
It works, thanks!
