### ISSUE TITLE
Most referenced libraries & Most followed libraries: Can we have more than 10?

### ISSUE THREAD

**Issue by marclaporte** [versioneye/versioneye_issues#9]
As seen here:
https://www.versioneye.com/JavaScript
https://www.versioneye.com/php
...

Ideally, we'd have a top-100 for each.

Thanks!

**Comment by marclaporte** [comment]
For example, with https://packagist.org/explore/popular, we can discover popular libs.

Thanks!

**Comment by reiz** [comment]
Yes. That's a good point. You are not the first one asking for this feature ;)

**Comment by reiz** [comment]
@marclaporte Totally forgot this ticket. That is already implemented since a couple weeks :-) Here are ALL PHP packages sorted by references: https://www.versioneye.com/PHP/most_referenced

**Comment by marclaporte** [comment]
Thanks Robert! You are great!

I added the link here (a good general guide to picking software)
https://suite.tiki.org/Tiki+Suite+Component+criteria

Best regards,

M ;-)

**Comment by reiz** [comment]
Awesome. Thanks for the back link :-)
